apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller
roleRef:
  name: controller
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: controller
  kind: ServiceAccount
