apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
- ../../controller
namePrefix: gcpauth-
patches:
- path: controller-deploy.yaml
- path: controller-certificate.yaml
- path: controller-crb.yaml
