apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpod
  labels:
    app.kubernetes.io/instance: devpod
spec:
  replicas: 0
  template:
    spec:
      labels:
        kapp.k14s.io/app: "1619191709372783000" # {"$kpt-set": "kapp-tag"}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: controller
      schedulerName: default-scheduler
      containers:
      - name: builder
        image: builder
        command: ["/bin/sleep", "infinity"]
        ports:
        - name: webhook-server
          protocol: TCP
          containerPort: 9443
        volumeMounts:
        - name: cert
          readOnly: true
          mountPath: /tmp/k8s-webhook-server/serving-certs
        - name: workspace
          readOnly: false
          mountPath: /root
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: devpod-workspace
      - name: cert
        secret:
          defaultMode: 420
          secretName: controller-tls
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
