apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: policies
resources:
- ../../bases/namespace-resources
- ../gcpworkload
- ../gcpauth
- ../node
commonLabels:
  app.kubernetes.io/component: controller
  app.kubernetes.io/name: k8s-policies-controller
transformers:
- code-usage-labeltransformer.yaml
