apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: k8s-policies-controller
    usage: build
  name: devpod-workspace
  namespace: policies
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
