apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- node-controller-clusterrole.yaml
- node-mutwebhookcfg.yaml
- profiles.node.policies.nuxeo.io-crd.yaml
commonlabels:
  app.kubernetes.io/instance: node
components:
- ../controller
transformers:
- |-
  apiVersion: builtin
  kind: PrefixSuffixTransformer
  metadata:
    name: controller
  prefix: node-
  fieldSpecs:
  - kind: Certificate
    path: metadata/name
  - kind: ClusterRole
    path: metadata/name
  - kind: ClusterRoleBinding
    path: metadata/name
  - kind: Deployment
    path: metadata/name
  - kind: ServiceAccount
    path: metadata/name
  - kind: Service
    path: metadata/name
