apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- node-controller-clusterrole.yaml
- node-mutwebhookcfg.yaml
- profiles.node.policies.nuxeo.io-crd.yaml
- controller
commonlabels:
  app.kubernetes.io/instance: node
