apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-controller
  creationTimestamp: null
rules:
- resources:
  - namespaces
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - profiles
  apiGroups:
  - node.profile.nuuxeo.io
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - profiles/status
  apiGroups:
  - node.profile.nuuxeo.io
  verbs:
  - get
  - patch
  - update
