apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases/devpod
commonLabels:
  app.kubernetes.io/instance: gcpworkload
patches:
- path: devpod-deploy.yaml
transformers:
- gcpworkload-prefixsuffixtransformer.yaml
