namespace: policies
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- devpod-cm.yaml
- devpod-workspace-persistentvolumeclaim.yaml
- gcpauth-devpod-deploy.yaml
- gcpworkload-devpod-deploy.yaml
- node-devpod-deploy.yaml
commonLabels:
  kapp.k14s.io/app: "1619191709372783000"
images:
- name: golang
  newTag: 1.15-buster
