apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: devpod
  name: node-devpod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: node
      app.kubernetes.io/name: k8s-policies-controller
      kapp.k14s.io/app: "1619191709372783000"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: node
        app.kubernetes.io/name: k8s-policies-controller
        kapp.k14s.io/app: "1619191709372783000"
    spec:
      containers:
        - image: golang:1.14-buster
          imagePullPolicy: Always
          name: dev
          command: [ "/usr/bin/tail", "-f", "/dev/null"]
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /root
              name: workspace
              readOnly: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: node-controller-tls
        - name: workspace
          persistentVolumeClaim:
            claimName: devpod-workspace
      dnsPolicy: ClusterFirst
      serviceAccountName: node-controller
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
