---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: gcpworkloadpolicyprofile-controller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - iam.cnrm.cloud.google.com
  resources:
  - iampolicymembers
  verbs:
  - '*'
- apiGroups:
  - gcpworkloadpolicy.nuxeo.io
  resources:
  - profiles
  verbs:
  - "*"
- apiGroups:
  - gcpworkloadpolicy.nuxeo.io
  resources:
  - profiles/status
  verbs:
  - "*"
