apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: policies/gcpworkloadpolicyprofile-controller-tls
  name: gcpworkloadpolicyprofile
webhooks:
- clientConfig:
    caBundle: ""
    service:
      name: gcpworkloadpolicyprofile-controller
      namespace: default
      path: /mutate-v1-serviceaccounts
      port: 443
  failurePolicy: Ignore
  name: gcpworkloadpolicyprofile-controller.policies.svc.cluster.local
  objectSelector:
    matchExpressions:
    - key: app
      operator: NotIn
      values:
      - k8s-policy-controller
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - DELETE
    resources:
    - serviceaccounts
  sideEffects: NoneOnDryRun
  timeoutSeconds: 5
