apiVersion: nodepolicy.nuxeo.io/v1alpha1
kind: NodePolicyProfile
metadata:
  name: stateless
spec:
  nodeSelector:
    type: "stateless"
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "stateless"
    effect: "NoSchedule"
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: type
          operator: In
          values:
          - stateless
      weight: 1
