apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- policies-ns.yaml
- selfsigned-issuer.yaml
- controller-ca-certificate.yaml
- controller-issuer.yaml
commonlabels:
  app.kubernetes.io/component: namespace
