apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gcpauth-controller-clusterrole.yaml
- gcpauth-mutwebhookcfg.yaml
- profiles.gcpauth.policies.nuxeo.io-crd.yaml
- controller
commonlabels:
  app.kubernetes.io/instance: gcpauth
