apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gcpauth-controller-certificate.yaml
- gcpauth-controller-clusterrole.yaml
- gcpauth-controller-crb.yaml
- gcpauth-controller-deploy.yaml
- gcpauth-controller-sa.yaml
- gcpauth-controller-svc.yaml
- gcpauth-mutwebhookcfg.yaml
- profiles.gcpauth.policies.nuxeo.io-crd.yaml
commonLabels:
  app.kubernetes.io/component: controller
  app.kubernetes.io/instance: gcpauth
