kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/instance: gcpworkload
  app.kubernetes.io/component: controller
resources:
- gcpworkload-controller-certificate.yaml
- gcpworkload-controller-clusterrole.yaml
- gcpworkload-controller-crb.yaml
- gcpworkload-controller-deploy.yaml
- gcpworkload-controller-sa.yaml
- gcpworkload-controller-svc.yaml
- gcpworkload-mutwebhookcfg.yaml
- profiles.gcpworkload.policy.nuxeo.io-crd.yaml
