apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  template:
    spec:
      containers:
      - name: controller
        args:
        - --zap-devel
        - --zap-log-level=debug
        - --kind=gcpworkload
      volumes:
      - name: cert
        secret:
          secretName: gcpworkload-controller-tls
