apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: node
    app.kubernetes.io/name: k8s-policies-controller
  name: node-controller
