apiVersion: v1
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  annotations:
    cert-manager.io/allow-direct-injection: "true"
  name: gcpauthpolicyprofile-controller-tls
type: kubernetes.io/tls
