apiVersion: nodepolicy.nuxeo.io/v1alpha1
kind: Profile
metadata:
  name: nodepolicyprofile-test
spec:
  podSelector:
    matchLabels:
      nodepolicyprofile/test: "true"
  nodeSelector:
    type: "stateless"
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "stateless"
    effect: "NoSchedule"
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: type
          operator: In
          values:
          - stateless
      weight: 1
