apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test
  labels:
    test: node-webhook
spec:
  replicas: 0
  selector:
    matchLabels:
      node/test: "true"
  template:
    metadata:
      labels:
        node/test: "true"
      creationTimestamp: null
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: node-controller
      schedulerName: default-scheduler
      containers:
      - name: test
        image: golang:1.14-buster
        command: ["/usr/bin/env", "tail", "-f", "/dev/null"]
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
