apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test: node-webhook
  name: node-test
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      node/test: "true"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        node/test: "true"
    spec:
      containers:
        - command: ["/usr/bin/env", "tail", "-f", "/dev/null"]
          image: golang:1.14-buster
          imagePullPolicy: Always
          name: test
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      serviceAccountName: node-controller
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
