apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  annotations:
    gcpauth.policies.nuxeo.io/profile: policies-test
    gcpworkload.policies.nuxeo.io/profile: policies-test
    node.policies.nuxeo.io/profile: policies-test
