apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpworkload-controller
  creationTimestamp: null
rules:
- resources:
  - namespaces
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - profiles
  apiGroups:
  - gcpworkload.profile.nuuxeo.io
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - profiles/status
  apiGroups:
  - gcpworkload.profile.nuuxeo.io
  verbs:
  - get
  - patch
  - update
- resources:
  - iampolicymembers
  apiGroups:
  - iam.cnrm.cloud.google.com
  verbs:
  - '*'
