apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gcpworkload-controller-certificate.yaml
- gcpworkload-controller-clusterrole.yaml
- gcpworkload-controller-crb.yaml
- gcpworkload-controller-deploy.yaml
- gcpworkload-controller-sa.yaml
- gcpworkload-controller-svc.yaml
- gcpworkload-mutwebhookcfg.yaml
- profiles.gcpworkload.policies.nuxeo.io-crd.yaml
commonLabels:
  app.kubernetes.io/component: controller
  app.kubernetes.io/instance: gcpworkload
