apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gcpworkload-controller-clusterrole.yaml
- gcpworkload-mutwebhookcfg.yaml
- profiles.gcpworkload.policies.nuxeo.io-crd.yaml
- controller
commonlabels:
  app.kubernetes.io/instance: gcpworkload
