apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nodepolicyprofile-controller
spec:
  commonName: nodepolicyprofile-controller.policies.svc
  dnsNames:
  - nodepolicyprofile-controller.policies.svc
  - nodepolicyprofile-controller.policies.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: policy-controller
  secretName: nodepolicyprofile-controller-tls
