apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: policies/nodepolicyprofile-controller
  name: nodepolicyprofile
webhooks:
- clientConfig:
    caBundle: ""
    service:
      name: nodepolicyprofile-controller
      namespace: default
      path: /mutate-v1-pods
      port: 443
  failurePolicy: Ignore
  name: nodepolicyprofile-controller.policies.svc.cluster.local
  objectSelector:
    matchExpressions:
    - key: app
      operator: NotIn
      values:
      - k8s-policy-controller
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  timeoutSeconds: 5
