apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: nodepolicyprofile
    app.kubernetes.io/name: k8s-policy-controller
  name: nodepolicyprofile-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodepolicyprofile-controller
subjects:
- kind: ServiceAccount
  name: nodepolicyprofile-controller
