apiVersion: v1
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  annotations:
    cert-manager.io/allow-direct-injection: "true"
  labels:
    app.kubernetes.io/instance: nodepolicyprofile
    app.kubernetes.io/name: k8s-policy-controller
  name: nodepolicyprofile-controller-tls
type: kubernetes.io/tls
